version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
    entrypoint: ["./entrypoint.sh"]
    env_file:
      - .env


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Expose only Nginx on port 80
      - "4200:4200"  # Expose port 4200
      - "8001:8001"  # Expose port 8001
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
    driver: local